# the filter currently checks for words that are 3 or more characters.
ass: "*ss"
asses: "*ss*s"
asshole: "*ssh*l*"
bastard: b*st*rd
bitch: b*tch
cock: c*ck
cocks: c*cks
cum: c*m
cunt: c*nt
cunts: c*nts
dildo: d*ld*
dick: d*ck
ejaculate: "*j*c*l*t*"
ejaculated: "*j*c*l*t*d"
fuck: f*ck
fucks: f*cks
fuk: f*k
horny: h*rny
fuck: f*ck
phuk: p**k
phuq: ph*q
pis: p*ss
piss: p*ss
porn: p*rn
pornography: p*rn*gr*phy
pornos: p*rn*s
prick: pr*ck
pricks: pr*cks
pussies: p*ss**s
pussy: p*ssy
shit: sh*t
shits: sh*ts
shitty: sh*tty
shity: sh*tty
slut: sl*t