default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.postgresql
  adapter: postgresql
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: db/test.postgresql
  adapter: postgresql
  pool: 5
  timeout: 5000

production:
  <<: *default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: db/production.postgresql